apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebsite-deployment  # Name of the deployment
spec:
  replicas: 2  # Number of replicas (pods)
  selector:
    matchLabels:
      app: mywebsite  # Selector to match the pods
  template:
    metadata:
      labels:
        app: mywebsite  # Label for the pods, should match the selector
    spec:
      containers:
        - name: mywebsite  # Name of the container
          image: tecknosap.azurecr.io/mywebsite:v1  # Docker image reference
          ports:
            - containerPort: 80  # Expose container on port 80
