apiVersion: v1
kind: Service
metadata:
  name: mywebsite-service  # Name of the service
spec:
  selector:
    app: mywebsite  # Ensure this matches the pod labels
  ports:
    - protocol: TCP
      port: 80  # Expose service on port 80
      targetPort: 80  # Forward traffic to port 80 on the pods
  type: LoadBalancer  # Expose service to the internet via LoadBalancer
