apiVersion: v1
kind: Service
metadata:
  name: mywebsite-service
spec:
  selector:
    app: mywebsite  # Ensure this matches the pod labels
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
